name: XML Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Install prerequisite libxml2-utils
        run: sudo apt-get install -y -qq libxml2-utils

      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Copy markup xsd
        run: curl -OJ https://github.com/bleachbit/bleachbit/blob/v4.4.2/doc/cleaner_markup_language.xsd

      - name: Conduct XML Test
        run: xmllint ./Cleaners/*.xml --schema cleaner_markup_language.xsd --noout
