name: XML Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Install prerequisite libxml2-utils
        run: sudo apt-get install -y -qq libxml2-utils

      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Copy markup xsd
        run: curl -OJ https://raw.githubusercontent.com/bleachbit/bleachbit/v4.4.2/doc/cleaner_markup_language.xsd

      - name: Conduct XML Test
        run: xmllint ./Cleaners/*.xml --schema cleaner_markup_language.xsd --noout

      - name: Ensure no XML has the same cleaner.id
        run: |
          # ensure that no XML files in Cleaners directory have the same cleaner.id attribute as other files
          for f in Cleaners/*.xml; do
              x=$(xmllint --xpath "//cleaner/@id" $f)
              # For the files that are not f, check if they have the same cleaner.id attribute

              for g in Cleaners/*.xml; do
                  if [ "$f" == "$g" ]; then
                      # If the file is the same as f, skip it
                      continue
                  fi

                  y=$(xmllint --xpath "//cleaner/@id" $g)
                  if [ "$x" == "$y" ]; then
                      echo "Error: $f and $g have the same cleaner.id attribute"
                      exit 1
                      fi
              done
              echo "$f cleaner.id attribute is unique"
          done
