name: XML Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Install prerequisite libxml2-utils
        run: sudo apt-get install -y -qq libxml2-utils

      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: bleachbit-cleaners

      - name: Checkout official bleachbit repository
        uses: actions/checkout@v3
        with:
          path: bleachbit
          repository: bleachbit/bleachbit
        
      - name: Copy markup xsd
        run: cp -v ./bleachbit/doc/cleaner_markup_language.xsd ./bleachbit-cleaners/Cleaners/cleaner_markup_language.xsd

      - name: Conduct XML Test
        run: |
          for xml in $(ls -b *.xml)
          do
          xmllint $xml --schema cleaner_markup_language.xsd
          done
        working-directory: ./bleachbit-cleaners/Cleaners
